# Config file for air (https://github.com/cosmtrek/air)
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o main ./cmd/server"
  bin = "main"
  full_bin = "./main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  delay = 1000
  stop_on_error = true

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
