services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: always
    working_dir: /app
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - air-temp:/temp
    command:
      - air


volumes:
  air-temp:
