# Use official lightweight Go image
FROM golang:1.24-alpine AS builder
WORKDIR /app
RUN apk add --no-cache gcc musl-dev sqlite-dev git curl
COPY go.mod go.sum ./
RUN go mod download
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
COPY . .
EXPOSE 8080
CMD ["/main"]
